services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
    user: root
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt:ro
      - ./install-plugins.sh:/usr/local/bin/install-plugins.sh:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    entrypoint: ["/usr/bin/tini", "--"]
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/install-plugins.sh
        exec su jenkins -c "/usr/local/bin/jenkins.sh"

volumes:
  jenkins_home:
